[package]
name = "stacks"
version = "0.1.0"
edition = "2021"

[lib]
name = "stacks"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24.0", features = ["extension-module"] }
rusty-stacks = { path = ".." } # references the backend
